git config --global user.name "$GITUSERNAME"
git config --global user.email "$GITEMAIL"

git config --global alias.l "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
git config --global alias.a "add --all"
git config --global alias.d "diff"
git config --global alias.s "status"
git config --global alias.b "branch -a"
git config --global alias.f "fetch -p"
git config --global alias.bd "branch -d"
git config --global alias.ca "commit -am"
git config --global alias.cm "commit -m"
git config --global alias.rh "reset --hard"
git config --global alias.ph "push origin head"
git config --global alias.pd "pull origin develop"
git config --global alias.pm "pull origin master"
git config --global alias.co "checkout"
git config --global alias.com "checkout master"
git config --global alias.cod "checkout develop"